import { chromium, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir=fileURLToPath(new URL('../../../artifacts/phase-a/visual-review/', import.meta.url));const records=[];
let browser;
async function capture(page,name,note=''){
 const frame=page.getByRole('region',{name:'Game frame',exact:true});
 const mobile=await page.evaluate(()=>matchMedia('(pointer: coarse)').matches);if(!mobile){const v=page.viewportSize();const d=await page.evaluate(()=>devicePixelRatio);await expect(frame).toHaveAttribute('data-scale',String(Math.floor(Math.min(v.width*d/240,v.height*d/160))));}const scale=Number(await frame.getAttribute('data-scale'));const box=await frame.boundingBox();
 const dpr=await page.evaluate(()=>devicePixelRatio);const viewport=page.viewportSize();
 const transition=await page.locator('[data-transition]').evaluateAll(es=>es.map(e=>({type:e.dataset.transition,frame:e.dataset.frame})));
 await page.screenshot({path:path.join(dir,name+'.png'),animations:'allow'});
 records.push({filename:name+'.png',viewport,dpr,scale,frame:box,transition,note});fs.writeFileSync(path.join(dir,'captures.json'),JSON.stringify(records,null,2));console.log('CAPTURE',name,viewport,dpr,scale);
}
async function newPage(viewport={width:960,height:640},extra={}){const context=await browser.newContext({viewport,deviceScaleFactor:1,...extra});return context.newPage();}
const status=p=>p.getByRole('status',{name:'Game state',exact:true});
async function advance(p){const r=p.getByRole('button',{name:'Reveal dialogue',exact:true});if(await r.isVisible())await r.click();const c=p.getByRole('button',{name:'Continue dialogue',exact:true});await expect(c).toBeVisible();await c.click();await p.waitForTimeout(60);}
async function drainUntil(p,locator){for(let i=0;i<50;i++){if(await locator.isVisible() && await p.getByRole('button',{name:/dialogue/}).count()===0)return;if(await p.getByRole('button',{name:/dialogue/}).count())await advance(p);else await p.waitForTimeout(150);}throw Error('drain timed out '+await p.locator('body').innerText());}
async function start(p,intro=false){await p.goto('http://127.0.0.1:3100/');await expect(p.getByRole('button',{name:'PRESS START'})).toBeEnabled();await p.getByRole('button',{name:'PRESS START'}).click();await expect(p.getByRole('button',{name:/dialogue/})).toBeVisible();if(intro){const r=p.getByRole('button',{name:'Reveal dialogue'});if(await r.isVisible())await r.click();await capture(p,'02-intro-narration','Current narration presentation.');}
 for(let i=0;i<30;i++){if((await status(p).innerText()).includes('Flow OVERWORLD'))break;if(await p.getByRole('button',{name:/dialogue/}).count())await advance(p);else await p.waitForTimeout(150);}await expect(status(p)).toContainText('Flow OVERWORLD');}
async function step(p,key,x,y){await p.keyboard.down(key);await expect(status(p)).toContainText(`movement ${x},${y}`);await p.keyboard.up(key);await expect(status(p)).toContainText(`player tile ${x},${y}`);}
async function choose(p,group,name){const b=group.getByRole('button',{name,exact:true});await b.click();if(await b.count()&&await b.isVisible())await b.click();await p.waitForTimeout(130);}
(async()=>{browser=await chromium.launch({headless:true});
 let p=await newPage({width:1440,height:900},{deviceScaleFactor:2});await p.goto('http://127.0.0.1:3100/');await expect(p.getByRole('button',{name:'PRESS START'})).toBeEnabled();await capture(p,'01-title-largest-fit-desktop','Largest-fit desktop n=11. Title graphic is current text treatment, unfinished final production title art.');await p.context().close();
 p=await newPage();await start(p,true);await capture(p,'03-overworld-4x','Unfinished production terrain/building/character art.');await p.setViewportSize({width:720,height:480});await capture(p,'04-overworld-3x','Unfinished production terrain/building/character art.');await p.setViewportSize({width:240,height:160});await capture(p,'05-native-1x','Native 240×160 inspection; unfinished world art.');await p.setViewportSize({width:960,height:640});
 await p.keyboard.press('KeyX');await p.waitForTimeout(200);await capture(p,'06-player-menu-unavailable','X leaves the current overworld visible: Player Menu is not implemented. This is absence evidence, not a menu screenshot.');
 await step(p,'ArrowDown',7,6);await step(p,'ArrowDown',7,7);for(let x=8;x<=15;x++)await step(p,'ArrowRight',x,7);
 await expect(p.getByRole('button',{name:/dialogue/})).toBeVisible();if(await p.getByRole('button',{name:'Reveal dialogue'}).isVisible())await p.getByRole('button',{name:'Reveal dialogue'}).click();await capture(p,'07-overworld-dialogue-4x','Unfinished production world art.');await p.setViewportSize({width:720,height:480});await capture(p,'08-overworld-dialogue-3x','Unfinished production world art.');await p.setViewportSize({width:960,height:640});
 await drainUntil(p,p.getByRole('group',{name:'Audience selection'}));await capture(p,'09-audience-selection','Unfinished world art beneath audience window.');
 await choose(p,p.getByRole('group',{name:'Audience selection'}),'I’m hiring');await expect(p.getByRole('main',{name:'Interview challenge'})).toBeVisible();await p.waitForTimeout(450);await capture(p,'10-vs-recruiter','Unfinished portrait/sprite production art. Actual main game encounter.');
 await drainUntil(p,p.getByRole('group',{name:'Battle commands'}));await capture(p,'13-battle-command-grid','Unfinished trainer/project portrait art.');await p.keyboard.press('Enter');await expect(p.getByRole('group',{name:'Interview topics'})).toBeVisible();await capture(p,'14-topic-selection','Unfinished battle portrait art.');await p.keyboard.press('Enter');await expect(p.getByRole('button',{name:/dialogue/})).toBeVisible();await advance(p);await expect(p.getByRole('button',{name:/dialogue/})).toBeVisible();if(await p.getByRole('button',{name:'Reveal dialogue'}).isVisible())await p.getByRole('button',{name:'Reveal dialogue'}).click();await capture(p,'15-two-line-answer','Actual authored answer page; unfinished battle portrait art.');
 await drainUntil(p,p.getByRole('group',{name:'Battle commands'}));
 await choose(p,p.getByRole('group',{name:'Battle commands'}),'PARTY');await expect(p.getByRole('main',{name:'Choose a project'})).toBeVisible();await p.waitForTimeout(350);await capture(p,'16-party','Current six-project window layout; final project visual assets unfinished.');
 await p.keyboard.press('ArrowDown');await p.keyboard.press('Enter');await p.locator('[data-transition="switch-short"]').waitFor();await capture(p,'17-project-switch-transition','Actual project-switch transition; unfinished battle portrait art.');await expect(p.getByRole('button',{name:/dialogue/})).toBeVisible();if(await p.getByRole('button',{name:'Reveal dialogue'}).isVisible())await p.getByRole('button',{name:'Reveal dialogue'}).click();await capture(p,'18-project-switch-sendout','Actual changed project/send-out window; unfinished battle portrait art.');
 await drainUntil(p,p.getByRole('group',{name:/^(Battle commands|Interview topics)$/}));if(await p.getByRole('group',{name:'Interview topics'}).isVisible())await p.keyboard.press('Backspace');await choose(p,p.getByRole('group',{name:'Battle commands'}),'EXIT');await expect(status(p)).toContainText('Flow OVERWORLD');await p.waitForTimeout(300);
 await step(p,'ArrowDown',15,8);for(let x=16;x<=21;x++)await step(p,'ArrowRight',x,8);await step(p,'ArrowUp',21,7);await step(p,'ArrowUp',21,6);await step(p,'ArrowUp',21,5);await p.keyboard.down('ArrowRight');await p.waitForTimeout(35);await p.keyboard.up('ArrowRight');await capture(p,'19-doorway-before','Door entry is interaction-triggered in current world; transition animates automatically. Unfinished building/player art.');await p.keyboard.press('Enter');await p.locator('[data-transition="door"]').waitFor();await capture(p,'20-doorway-transition','Actual automatic door transition following interaction; entry on walking alone is not implemented.');await expect(status(p)).toContainText('Map m1-interior-test');await p.waitForTimeout(250);await capture(p,'21-doorway-after','Actual interior arrival; unfinished interior/player art.');await p.context().close();
 for(const [audience,name] of [['ENGINEER','11-vs-engineer'],['FRIEND','12-vs-friend']]){p=await newPage();await p.goto('http://127.0.0.1:3100/dev/battle');await p.getByLabel('Audience').selectOption(audience);await p.getByRole('button',{name:'Start battle'}).click();await expect(p.getByRole('main',{name:'Interview challenge'})).toBeVisible();await p.waitForTimeout(450);await capture(p,name,'Actual shared BattleOrchestrator via dev battle entry; unfinished portrait/sprite production art.');await p.context().close();}
 p=await newPage({width:390,height:844},{deviceScaleFactor:3,hasTouch:true,isMobile:true});await start(p);await capture(p,'22-touch-overworld','Actual coarse-pointer touch controls; unfinished world production art.');await p.context().close();
 await browser.close();console.log('DONE',records.length);
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
