import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs';
import {decodePng,cropPixels,histogram} from '../helpers/png';
import {palette} from '../../src/ui/kit/palette';
import {viewportGeometry} from '../../src/ui/kit/viewportGeometry';
import {rasterText} from '../../src/ui/kit/bitmap';
import {AXE_SCRIPT} from '../helpers/axe';
import musicMetadata from '../../assets-src/audio/music/decoded-metadata.json';
import {getParty} from '../../src/content/party';
import {getProject} from '../../src/content/registry';
import {getBattleSummary} from '../../src/content/battle-presentation';
import type {AudienceId} from '../../src/domain/types';
const out='artifacts/phase-11';
test.setTimeout(180_000);
async function tick(p:Page,ms=100){for(let t=0;t<ms;t+=25)await p.clock.runFor(Math.min(25,ms-t));}
async function key(p:Page,key:string,ms=120){await p.keyboard.press(key);await tick(p,ms);}
async function drain(p:Page,capture?:()=>Promise<void>){
 let loops=0;while(await p.getByRole('button',{name:/dialogue/}).count()){
  expect(loops++).toBeLessThan(180);
  if(await p.getByRole('button',{name:'Reveal dialogue'}).isVisible())await key(p,'a',20);
  if(capture){await capture();capture=undefined;}
  if(await p.getByRole('button',{name:'Continue dialogue'}).isVisible())await key(p,'a',20);else await tick(p,50);
 }
}
function recorder(p:Page,dpr:number,file:string,clocked=true){const records:object[]=[];return async(name:string)=>{
 const available=await p.evaluate(()=>{const style=getComputedStyle(document.querySelector('[data-safe-area]')!);return {width:visualViewport?.width??innerWidth,height:visualViewport?.height??innerHeight,touch:!!document.querySelector('.touch-controller'),insets:{top:parseFloat(style.paddingTop)||0,right:parseFloat(style.paddingRight)||0,bottom:parseFloat(style.paddingBottom)||0,left:parseFloat(style.paddingLeft)||0}};});
 const n=viewportGeometry(available.width,available.height,dpr,available.touch,available.insets).n,frame=p.getByRole('region',{name:'Game frame'});await expect(frame).toHaveAttribute('data-scale',String(n));if(clocked)await tick(p,50);if(name.startsWith('title-')){for(let i=0;i<30&&await p.getByRole('button',{name:'PRESS START'}).evaluate(el=>getComputedStyle(el).opacity)==='0';i++)await tick(p,50);}await expect.poll(()=>p.locator('[data-bitmap]:not([data-ready])').count()).toBe(0);await expect.poll(async()=>Math.round((await frame.boundingBox())!.width*dpr)).toBe(240*n);await expect.poll(async()=>Math.round((await frame.boundingBox())!.height*dpr)).toBe(160*n);await p.screenshot({path:`${out}/${name}.png`});records.push({filename:name+'.png',viewportCSS:p.viewportSize(),dpr,integerScale:n,physicalSurface:{width:240*n,height:160*n}});fs.writeFileSync(`${out}/${file}`,JSON.stringify(records,null,2));
};}
async function start(p:Page,{intro=false,touch=false}={}){
 await p.addInitScript(({intro})=>{sessionStorage.setItem('uw.progress.v1',JSON.stringify({projectsVisited:[],battlesWon:0,introSeen:!intro,firstEncounterDone:false}));localStorage.setItem('uw.hints.v1',JSON.stringify({seenHowToPlay:false,seenBattleUI:true,seenFirstMove:true,seenFirstInteract:true,seenPokedex:false,seenTrainerCard:false}));localStorage.setItem('uw.settings.v1',JSON.stringify({musicMuted:false,soundMuted:false,textSpeed:'normal',animationReduced:false,reducedMotion:false}));},{intro});
 await p.clock.install();await p.goto('/');await expect(p.getByRole('button',{name:'PRESS START'})).toBeEnabled();await p.clock.pauseAt(await p.evaluate(()=>Date.now()+100));if(touch)await p.getByRole('button',{name:'A confirm'}).tap();else await p.keyboard.press('a');await tick(p,600);
}
async function step(p:Page,keyName:string,to:string){await p.keyboard.down(keyName);await tick(p,50);await p.keyboard.up(keyName);await tick(p,400);await expect(p.getByRole('status',{name:'Game state'})).toContainText(`player tile ${to};`);}
async function axe(p:Page){await p.clock.resume();await p.addScriptTag({path:AXE_SCRIPT});const results=await p.evaluate(async()=>{const engine=(window as unknown as {axe:{run:()=>Promise<{violations:{id:string}[]}>}}).axe;return (await engine.run()).violations.map(v=>v.id);});await p.clock.pauseAt(await p.evaluate(()=>Date.now()+100));expect(results).toEqual([]);return results;}
test('P11 swatch: every authored glyph and palette pixel at DPR 1–3 × integer scales 1–8',async({browser})=>{
 fs.mkdirSync(out,{recursive:true});const results=[];
 for(const dpr of [1,2,3]){const c=await browser.newContext({deviceScaleFactor:dpr}),p=await c.newPage();
  for(let n=1;n<=8;n++){
   await p.setViewportSize({width:Math.ceil(240*n/dpr)+2,height:Math.ceil(160*n/dpr)+2});await p.goto('/dev/kit?swatch=p11');const frame=p.getByRole('region',{name:'Game frame'});await expect(frame).toHaveAttribute('data-scale',String(n));await expect.poll(()=>p.locator('[data-bitmap]:not([data-ready])').count()).toBe(0);
   const image=decodePng(await p.screenshot({path:`${out}/swatch-dpr${dpr}-${n}x.png`})),bounds=(await frame.boundingBox())!,surface=cropPixels(image,Math.round(bounds.x*dpr),Math.round(bounds.y*dpr),240*n,160*n),stats=histogram(surface.data,Object.values(palette));
   const text=await p.locator('[data-bitmap-text]').evaluateAll(nodes=>nodes.map(el=>{const r=el.getBoundingClientRect(),d=(el as HTMLElement).dataset;return {text:d.bitmapText!,width:Number(d.nativeWidth),height:Number(d.nativeHeight),ink:d.ink!,shadow:d.shadow!,x:r.x,y:r.y};}));let mismatches=0;
   for(const sample of text){const actual=cropPixels(image,Math.round(sample.x*dpr),Math.round(sample.y*dpr),sample.width*n,sample.height*n),reference=rasterText(sample.text,sample.width,sample.height,n,sample.ink,undefined,sample.shadow);for(let i=0;i<reference.data.length;i+=4)if(reference.data[i+3]&&[0,1,2].some(ch=>actual.data[i+ch]!==reference.data[i+ch]))mismatches++;}
   results.push({filename:`swatch-dpr${dpr}-${n}x.png`,viewportCSS:p.viewportSize(),dpr,integerScale:n,physicalWidth:surface.width,physicalHeight:surface.height,...stats,glyphMismatches:mismatches});fs.writeFileSync(`${out}/raster-matrix.json`,JSON.stringify(results,null,2));expect(stats.intermediatePixels).toBe(0);expect(mismatches).toBe(0);
  }
  await c.close();
 }
});
test('P11 real opening → LOS → audience → VS → battle → summary → topics → answers → Party → switch → exact exit',async({browser})=>{
 fs.mkdirSync(out,{recursive:true});const c=await browser.newContext({viewport:{width:960,height:640}}),p=await c.newPage(),capture=recorder(p,1,'opening-battle-captures.json'),errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));
 // First-user narration and title remain the actual root route.
 await p.clock.install();await p.goto('/');await expect(p.getByRole('button',{name:'PRESS START'})).toBeEnabled();await p.clock.pauseAt(await p.evaluate(()=>Date.now()+100));await tick(p,900);
 for(const n of [1,3,4]){await p.setViewportSize({width:240*n,height:160*n});await capture(`title-${n}x`);}await p.setViewportSize({width:1440,height:900});await capture('title-largest-fit');await p.setViewportSize({width:960,height:640});await key(p,'a',600);await drain(p,()=>capture('intro'));await tick(p,2300);await expect(p.getByRole('status',{name:'Game state'})).toContainText('Flow OVERWORLD');await capture('tutorial-first-beat');await tick(p,3000);await capture('tutorial-exit-beat');await tick(p,3000);await capture('tutorial-enjoy-beat');await tick(p,2000);
 for(const n of [1,3,4]){await p.setViewportSize({width:240*n,height:160*n});await capture(`town-${n}x`);}await p.setViewportSize({width:960,height:640});await step(p,'ArrowDown','7,6');await step(p,'ArrowDown','7,7');for(let x=8;x<=14;x++)await step(p,'ArrowRight',`${x},7`);await p.keyboard.down('ArrowRight');await tick(p,50);await p.keyboard.up('ArrowRight');await tick(p,700);await capture('trainer-noticed');await tick(p,1300);await expect(p.getByRole('status',{name:'Game state'})).toContainText('Flow ENCOUNTER');await drain(p,()=>capture('challenger-dialogue'));await expect(p.getByRole('group',{name:'Audience selection'})).toBeVisible();await tick(p,1500);await capture('audience-selection');const audienceHeading=await p.locator('[data-bitmap-text="YOUR PERSPECTIVE?"]').boundingBox();expect(audienceHeading!.y).toBe(30*4);const audienceButton=p.getByRole('button',{name:'I’m hiring'});const audienceRow=(await audienceButton.boundingBox())!,audienceLabel=(await audienceButton.locator('[data-bitmap-text="RECRUITER"]').boundingBox())!;expect(audienceLabel.x-audienceRow.x).toBe(12*4);await audienceButton.click();await tick(p,100);await capture('vs-recruiter-entry');await tick(p,450);await capture('vs-recruiter-impact');await tick(p,450);await expect(p.getByRole('region', { name: 'Interview challenge'})).toBeVisible();await capture('vs-recruiter');await tick(p,250);await capture('vs-recruiter-name-reveal');expect((await p.locator('[data-bitmap-text="RECRUITER"]').boundingBox())!.y).toBe(98*4);await tick(p,1700);await expect(p.locator('[data-battle-view-ready]')).toHaveAttribute('data-battle-view-ready','true');await tick(p,1000);await drain(p);await expect(p.getByRole('status',{name:'Battle state'})).toContainText('Battle view root');
 for(const n of [1,3,4]){await p.setViewportSize({width:240*n,height:160*n});await capture(`actual-battle-command-${n}x`);}await p.setViewportSize({width:1440,height:900});await capture('actual-battle-largest-fit');await p.setViewportSize({width:960,height:640});await axe(p);
 await key(p,'a');await expect(p.locator('[data-action-hints]')).toHaveAttribute('data-action-hints',/B: BACK/);await drain(p,()=>capture('summary-before-topics'));await expect(p.getByRole('group',{name:'Interview topics'})).toBeVisible();await capture('topics-list');await key(p,'a');await drain(p,()=>capture('answer-depth-1'));await key(p,'a');await key(p,'a');await drain(p,()=>capture('answer-depth-2'));await key(p,'a');await key(p,'a');await drain(p,()=>capture('answer-depth-3'));await expect(p.getByRole('group',{name:'Interview topics'})).toBeVisible();await capture('leaf-return-back');
 await key(p,'b');await key(p,'a');await drain(p);await key(p,'ArrowDown');await key(p,'a',500);await expect(p.getByRole('region', { name: 'Choose a project'})).toBeVisible();for(const n of [1,3,4]){await p.setViewportSize({width:240*n,height:160*n});await capture(`party-recruiter-${n}x`);}await p.setViewportSize({width:960,height:640});const slots=await p.getByRole('region',{name:'Choose a project'}).locator('button[aria-pressed]').all();const bounds=await Promise.all(slots.map(slot=>slot.boundingBox()));for(let i=1;i<bounds.length;i++){expect(bounds[i]!.x).toBe(bounds[0]!.x);expect(bounds[i]!.y-bounds[i-1]!.y).toBe(80);expect(bounds[i-1]!.y+bounds[i-1]!.height).toBeLessThanOrEqual(bounds[i]!.y);}await key(p,'ArrowDown');await key(p,'a',1700);await drain(p,()=>capture('project-switch-speaking'));await expect(p.getByRole('group',{name:'Interview topics'})).toBeVisible();await capture('switched-project-topics');await key(p,'b');await expect(p.getByRole('group',{name:'Battle commands'})).toBeVisible();await p.evaluate(()=>{window.__openedUrls=[];window.open=(url,target,features)=>{window.__openedUrls.push({url:String(url),target:target??'',features:features??''});return null;};});const link=p.getByRole('button',{name:'LINK',exact:true});await link.click();await link.click();await tick(p,100);expect(await p.evaluate(()=>window.__openedUrls)).toEqual([{url:getProject(getParty('RECRUITER' as AudienceId)[1]!)!.links.primary.url,target:'_blank',features:'noopener,noreferrer'}]);await capture('actual-root-link');await key(p,'b',1400);await expect(p.getByRole('status',{name:'Game state'})).toContainText('Flow OVERWORLD');await expect(p.getByRole('status',{name:'Game state'})).toContainText('player tile 15,7; facing right;');await capture('exact-battle-return');expect(errors).toEqual([]);await c.close();
});
test('P11 all audiences: approved VS pairs, summaries and complete Parties',async({browser})=>{
 for(const audience of ['ENGINEER','FRIEND'] as AudienceId[]){const c=await browser.newContext({viewport:{width:960,height:640}}),p=await c.newPage(),capture=recorder(p,1,`${audience.toLowerCase()}-captures.json`);await start(p);await step(p,'ArrowDown','7,6');await step(p,'ArrowDown','7,7');for(let x=8;x<=14;x++)await step(p,'ArrowRight',`${x},7`);await p.keyboard.down('ArrowRight');await tick(p,50);await p.keyboard.up('ArrowRight');await tick(p,2000);await drain(p);const choice=p.getByRole('button',{name:audience==='ENGINEER'?'I’m an engineer':'I’m just visiting',exact:true});await choice.click();await choice.click();await tick(p,1100);await capture(`vs-${audience.toLowerCase()}`);await tick(p,2800);await drain(p);await key(p,'a');await drain(p,()=>capture(`summary-${audience.toLowerCase()}`));await capture(`topics-${audience.toLowerCase()}`);await axe(p);await key(p,'b');await key(p,'ArrowDown');await key(p,'a',500);const party=p.getByRole('region', { name: 'Choose a project'});await expect(party.locator('button[aria-pressed]')).toHaveCount(6);for(const id of getParty(audience))await expect(party.getByRole('button',{name:getProject(id)!.name,exact:true})).toBeVisible();await capture(`party-${audience.toLowerCase()}`);await c.close();}
 // Every summary adapter must remain sourced and substantive, including all Party members.
 for(const a of ['RECRUITER','ENGINEER','FRIEND'] as AudienceId[])for(const id of getParty(a))expect(getBattleSummary(id)).toContain(getProject(id)!.summary.pages[0]!);
});
test('P11 portfolio screens, first-open notices, full skill art, settings and EXIT at 1×/3×/4×',async({browser})=>{
 const c=await browser.newContext({viewport:{width:960,height:640}}),p=await c.newPage(),capture=recorder(p,1,'portfolio-captures.json');await start(p);await expect(p.getByRole('status',{name:'Game state'})).toContainText('Flow OVERWORLD');await key(p,'x',500);
 async function scales(name:string){for(const n of [1,3,4]){await p.setViewportSize({width:240*n,height:160*n});await capture(`${name}-${n}x`);}await p.setViewportSize({width:960,height:640});}
 async function choose(name:string){const item=p.getByRole('button',{name,exact:true});if(await item.getAttribute('aria-current')!=='true')await item.click();await key(p,'a',700);}
 await scales('player-menu');await choose('POKÉDEX');await scales('pokedex');await expect(p.getByRole('region',{name:'Pokédex'})).toContainText('POKÉDEX');await expect(p.locator('[data-portfolio-screen="Pokédex"] [data-portfolio-art]')).not.toHaveCount(0);await key(p,'a');await scales('skill-detail');await axe(p);await key(p,'b');await key(p,'b',500);
 await choose('PROJECTS');await scales('projects');await key(p,'a');await scales('project-detail');await axe(p);await key(p,'b');await key(p,'b',500);
 await choose('EXPERIENCE');await scales('experience');await key(p,'a');await scales('experience-detail');await axe(p);await key(p,'b');await key(p,'b',500);
 await choose('BAG');await scales('bag-documents');await key(p,'ArrowRight');await capture('bag-profiles');await key(p,'ArrowRight');await capture('bag-contact');await key(p,'ArrowRight');await capture('bag-extras');await key(p,'a');await key(p,'a');await scales('document-reading');await expect(p.locator('[data-action-hints]')).toHaveCount(1);await expect(p.locator('[data-action-hints]')).toHaveAttribute('data-action-hints','A: NEXT  B: BACK');await axe(p);await key(p,'b');await key(p,'b',500);
 await choose('UTTKARSH');await scales('trainer-card');await expect(p.getByRole('region',{name:'Trainer Card'})).toContainText('UTTKARSH MALVIYA');await expect(p.locator('[data-action-hints]')).toHaveAttribute('data-action-hints','B: BACK');await axe(p);await key(p,'b',500);
 await choose('OPTIONS');await scales('options');await choose('CONTROLS');await scales('controls');await expect(p.getByRole('region',{name:'Controls'})).toContainText('A / ENTER');await axe(p);await key(p,'b');await key(p,'b',500);
 await choose('EXIT');await scales('exit-confirmation');await expect(p.locator('[data-action-hints]')).toHaveCount(1);await expect(p.getByRole('button',{name:'NO',exact:true})).toHaveAttribute('aria-current','true');await key(p,'b');await p.setViewportSize({width:1440,height:900});await capture('player-menu-largest-fit');await key(p,'x',500);
 // The conventional navigation must keep native keyboard activation while the game is mounted.
 const about=p.getByRole('navigation',{name:'Portfolio pages'}).getByRole('link',{name:'About',exact:true});await about.focus();await p.keyboard.press('Enter');await expect(p).toHaveURL(/\/about$/);await c.close();
});
test('P11 touch menu/Bag paths and reduced-motion presentation preserve the canonical controller',async({browser})=>{
 const c=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true}),p=await c.newPage(),capture=recorder(p,3,'touch-captures.json');await start(p,{touch:true});await expect(p.getByRole('status',{name:'Game state'})).toContainText('Flow OVERWORLD');const controller=p.getByLabel('Touch controller');await expect(controller).toBeVisible();await capture('touch-overworld');await p.getByRole('button',{name:'Menu (X)'}).tap();await tick(p,500);await capture('touch-player-menu');await p.getByRole('button',{name:'A confirm'}).tap();await tick(p,600);await capture('touch-pokedex');await p.getByRole('button',{name:'A confirm'}).tap();await tick(p,120);await capture('touch-skill-detail');await p.getByRole('button',{name:'B back'}).tap();await tick(p,100);await p.getByRole('button',{name:'B back'}).tap();await tick(p,500);await p.getByRole('button',{name:'Bag (Y)'}).tap();await tick(p,500);await capture('touch-bag');await expect(p.getByRole('button',{name:'RESUME',exact:true})).toHaveAttribute('aria-current','true');
 for(const button of await controller.locator('button').all()){const r=(await button.boundingBox())!;expect(r.width).toBeGreaterThanOrEqual(48);expect(r.height).toBeGreaterThanOrEqual(48);}
 await p.getByRole('button',{name:'B back'}).tap();await tick(p,500);if(!await p.getByRole('navigation',{name:'Player Menu'}).count()){await p.getByRole('button',{name:'Menu (X)'}).tap();await tick(p,500);}await p.getByRole('button',{name:'OPTIONS',exact:true}).tap();await p.getByRole('button',{name:'OPTIONS',exact:true}).tap();await tick(p,700);await p.getByRole('button',{name:'REDUCED MOTION',exact:true}).tap();await p.getByRole('button',{name:'REDUCED MOTION',exact:true}).tap();await tick(p,100);await capture('touch-options-reduced-motion');await c.close();
 const desktop=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:2,reducedMotion:'reduce'}),q=await desktop.newPage(),proof=recorder(q,2,'reduced-motion-captures.json');await start(q);await expect(q.getByRole('status',{name:'Game state'})).toContainText('Flow OVERWORLD');await expect(q.getByRole('region',{name:'Game frame'})).toHaveAttribute('data-scale','11');await proof('largest-fit-dpr2-reduced-motion');await q.keyboard.down('ArrowDown');await tick(q,50);await q.keyboard.up('ArrowDown');await tick(q,100);await expect(q.getByRole('status',{name:'Game state'})).toContainText('movement 7,6');await expect(q.locator('canvas[data-world-art]')).toHaveAttribute('data-frameplayer','player-down-idle');await proof('reduced-motion-walk');await tick(q,400);await expect(q.getByRole('status',{name:'Game state'})).toContainText('player tile 7,6;');await key(q,'x',500);await proof('menu-reduced-motion');await desktop.close();
});
test('P11 real-time walking in four directions and unlocked scene music/mute transport',async({browser})=>{
 const c=await browser.newContext({viewport:{width:960,height:640},recordVideo:{dir:`${out}/recording`,size:{width:960,height:640}}}),p=await c.newPage(),capture=recorder(p,1,'walking-audio-captures.json',false);
 await p.addInitScript(()=>{
  sessionStorage.setItem('uw.progress.v1',JSON.stringify({projectsVisited:[],battlesWon:0,introSeen:true,firstEncounterDone:false}));localStorage.setItem('uw.hints.v1',JSON.stringify({seenHowToPlay:true,seenBattleUI:true,seenFirstMove:true,seenFirstInteract:true,seenPokedex:true,seenTrainerCard:true}));localStorage.setItem('uw.settings.v1',JSON.stringify({musicMuted:false,soundMuted:false,textSpeed:'instant',animationReduced:false,reducedMotion:false}));
  const events:{type:string;loop:boolean;duration:number}[]=[];Reflect.set(window,'__p11Audio',events);const original=AudioContext.prototype.createBufferSource;
  AudioContext.prototype.createBufferSource=function(){const source=original.call(this),start=source.start.bind(source),stop=source.stop.bind(source);source.start=(...args)=>{events.push({type:'start',loop:source.loop,duration:source.buffer?.duration??0});return start(...args);};source.stop=(...args)=>{events.push({type:'stop',loop:source.loop,duration:source.buffer?.duration??0});return stop(...args);};return source;};
 });
 const events=()=>p.evaluate(()=>Reflect.get(window,'__p11Audio') as {type:string;loop:boolean;duration:number}[]),world=p.getByRole('status',{name:'Game state'}),frames:object[]=[],poses=new Set<string>();
 await p.goto('/');await expect(p.getByRole('button',{name:'PRESS START'})).toBeEnabled();expect(await events()).toEqual([]);await p.keyboard.press('a');await expect(world).toContainText('Flow OVERWORLD');await expect.poll(async()=>(await events()).filter(e=>e.type==='start')).toHaveLength(1);expect((await events())[0]).toEqual({type:'start',loop:true,duration:musicMetadata.town.duration});await capture('audio-town-4x');
 async function move(key:string,x:number,y:number){await p.keyboard.down(key);await expect(world).toContainText(`movement ${x},${y}`);await p.keyboard.up(key);for(let sample=0;sample<30;sample++){const frame=await p.locator('canvas[data-world-art]').getAttribute('data-frameplayer');if(frame)poses.add(frame);if((await world.innerText()).includes(`player tile ${x},${y};`))break;await p.waitForTimeout(25);}await expect(world).toContainText(`player tile ${x},${y};`);}
 await move('ArrowLeft',6,5);await move('ArrowDown',6,6);await move('ArrowDown',6,7);
 for(const [direction,key,dx,dy] of [['up','ArrowUp',0,-1],['right','ArrowRight',1,0],['down','ArrowDown',0,1],['left','ArrowLeft',-1,0]] as const){
  const tile=(await world.innerText()).match(/player tile (\d+),(\d+)/)!;let x=Number(tile[1]),y=Number(tile[2]);for(let i=0;i<5;i++){x+=dx;y+=dy;await move(key,x,y);frames.push({direction,tile:{x,y},frame:await p.locator('canvas[data-world-art]').getAttribute('data-frameplayer'),camera:await p.locator('canvas[data-world-art]').evaluate(el=>({x:(el as HTMLCanvasElement).dataset.cameraX,y:(el as HTMLCanvasElement).dataset.cameraY}))});}await capture(`walking-${direction}-idle-4x`);for(const phase of [0,1,2])expect(poses.has(`player-${direction}-${phase}`),`${direction} walk pose ${phase}`).toBe(true);
 }
 await p.keyboard.press('x');await expect(p.getByRole('navigation',{name:'Player Menu'})).toBeVisible();await expect(p.locator('[data-transition]')).toHaveCount(0);const options=p.getByRole('button',{name:'OPTIONS',exact:true});await options.click();await options.click();await expect(p.getByRole('region',{name:'Options'})).toBeVisible();await expect(p.locator('[data-transition]')).toHaveCount(0);await p.keyboard.press('a');await expect.poll(async()=>(await events()).filter(e=>e.type==='stop')).toHaveLength(1);await p.keyboard.press('a');await expect.poll(async()=>(await events()).filter(e=>e.type==='start')).toHaveLength(2);await p.keyboard.press('b');await expect(p.getByRole('navigation',{name:'Player Menu'})).toBeVisible();await expect(p.locator('[data-transition]')).toHaveCount(0);await p.keyboard.press('b');await expect(p.getByRole('navigation',{name:'Player Menu'})).toHaveCount(0);
 for(let x=7;x<=15;x++)await move('ArrowRight',x,7);await expect(world).toContainText('Flow ENCOUNTER');let guard=0;while(!await p.getByRole('group',{name:'Audience selection'}).count()){expect(guard++).toBeLessThan(50);await p.keyboard.press('a');await p.waitForTimeout(40);}await p.keyboard.press('a');await expect(p.locator('[data-battle-view-ready]')).toHaveAttribute('data-battle-view-ready','true');await expect.poll(async()=>(await events()).filter(e=>e.type==='start')).toHaveLength(3);expect((await events()).filter(e=>e.type==='start')).toEqual([{type:'start',loop:true,duration:musicMetadata.town.duration},{type:'start',loop:true,duration:musicMetadata.town.duration},{type:'start',loop:true,duration:musicMetadata.battle.duration}]);
 for(let i=0;i<50&&(await p.getByRole('button',{name:/dialogue/}).count()||!await p.getByRole('group',{name:'Battle commands'}).count());i++){await p.keyboard.press('a');await p.waitForTimeout(80);}await expect(p.getByRole('group',{name:'Battle commands'})).toBeVisible();await expect(p.getByRole('button',{name:/dialogue/})).toHaveCount(0);await capture('audio-battle-4x');
 await p.keyboard.press('b');await expect(world).toContainText('Flow OVERWORLD');await expect(world).toContainText('player tile 15,7; facing right;');await expect.poll(async()=>(await events()).filter(e=>e.type==='start')).toHaveLength(4);expect((await events()).filter(e=>e.type==='start')[3]).toEqual({type:'start',loop:false,duration:musicMetadata.victory.duration});await capture('audio-victory-return-4x');
 await expect.poll(async()=>(await events()).filter(e=>e.type==='start'),{timeout:45_000}).toHaveLength(5);expect((await events()).filter(e=>e.type==='start')[4]).toEqual({type:'start',loop:true,duration:musicMetadata.town.duration});await expect(world).toContainText('Flow OVERWORLD');
 fs.writeFileSync(`${out}/walking-audio.json`,JSON.stringify({viewportCSS:p.viewportSize(),dpr:1,integerScale:4,walking:frames,observedPoses:[...poses],audio:await events(),video:'walking-four-directions-4x.webm'},null,2));const video=p.video()!;await c.close();await video.saveAs(`${out}/walking-four-directions-4x.webm`);
});
