import {test,expect,type Page,type Download} from '@playwright/test';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {decodePng,cropPixels,histogram} from '../helpers/png';
import art from '../../assets-src/portfolio/art.json';
import battleArt from '../../assets-src/battle/art.json';
import worldPalettes from '../../assets-src/world/palette-sheet.json';
import {palette} from '../../src/ui/kit/palette';
import {PORTFOLIO_PROJECTS,SKILLS} from '../../src/content/portfolio';
test.setTimeout(180000);
const output='artifacts/phase-b';
async function tick(p:Page,ms=400){for(let t=0;t<ms;t+=25)await p.clock.runFor(Math.min(25,ms-t));}
async function key(p:Page,key:string,wait=120){await p.keyboard.press(key);await tick(p,wait);}
async function start(p:Page,touch=false){await p.addInitScript(()=>{sessionStorage.setItem('uw.progress.v1',JSON.stringify({projectsVisited:[],battlesWon:0,introSeen:true,firstEncounterDone:true}));localStorage.setItem('uw.hints.v1',JSON.stringify({seenHowToPlay:true,seenBattleUI:true,seenFirstMove:true,seenFirstInteract:true,seenPokedex:true,seenTrainerCard:true}));});await p.clock.install();await p.goto('/');await expect(p.getByRole('button',{name:'PRESS START'})).toBeEnabled();await p.clock.pauseAt(await p.evaluate(()=>Date.now()+100));if(touch){await p.getByRole('button',{name:'A confirm'}).tap();await tick(p,700);}else await key(p,'Enter',700);await expect(p.getByRole('status',{name:'Game state'})).toContainText('Flow OVERWORLD');}
function recorder(p:Page,dpr:number,index:string){const captures:object[]=[];return async(filename:string,n:number)=>{
 const frame=p.getByRole('region',{name:'Game frame'});await expect(frame).toHaveAttribute('data-scale',String(n));await tick(p,30);const rect=(await frame.boundingBox())!,png=decodePng(await p.screenshot(process.env.POKEFOLIO_FLOW_SCREENSHOTS==='0'?{}:{path:`${output}/${filename}`})),pixels=cropPixels(png,Math.round(rect.x*dpr),Math.round(rect.y*dpr),240*n,160*n);let bad=0;
 for(let y=0;y<160;y++)for(let x=0;x<240;x++){const a=((y*n)*pixels.width+x*n)*4;for(let dy=0;dy<n;dy++)for(let dx=0;dx<n;dx++){const b=((y*n+dy)*pixels.width+x*n+dx)*4;if([0,1,2,3].some(c=>pixels.data[a+c]!==pixels.data[b+c]))bad++;}}
 const allowed=[...new Set([...Object.values(palette),...Object.values(art).flatMap(a=>a.palette.filter((c):c is string=>c!==null)),...Object.values(battleArt).flatMap(a=>a.palette.filter((c):c is string=>c!==null)),...Object.values(worldPalettes.tiles).flat(),...Object.values(worldPalettes.characters).flatMap(a=>Object.values(a)),'#283D38'])];const colors=histogram(pixels.data,allowed);
 expect(bad,`${filename}: native pixel blocks`).toBe(0);expect(colors.intermediatePixels,`${filename}: authored palette`).toBe(0);
 captures.push({filename,viewport:p.viewportSize(),dpr,integerScale:n,physicalPixels:{width:png.width,height:png.height},frameBounds:rect,pixelBlockMismatches:bad,intermediateColors:colors.intermediateColors,portfolioState:await p.getByRole('status',{name:'Portfolio state'}).textContent()});if(process.env.POKEFOLIO_FLOW_SCREENSHOTS!=='0')fs.writeFileSync(`${output}/${index}`,JSON.stringify(captures,null,2));
 };}
async function menuItem(p:Page,name:string){const row=p.getByRole('navigation',{name:'Player Menu'}).getByRole('button',{name,exact:true});if(await row.getAttribute('aria-current')!=='true')await row.click();await row.click();await tick(p,500);}
test('B4 production menu screens: native, 3x, 4x, catalogue, paging, options and EXIT',async({browser})=>{
 const c=await browser.newContext({viewport:{width:960,height:640}}),p=await c.newPage(),capture=recorder(p,1,'b4-captures.json');const errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));await start(p);await key(p,'x');const world=p.getByRole('status',{name:'Game state'}),anchor=(await world.innerText()).match(/Map [^;]+; room [^;]+; player tile [^;]+; facing [^;]+;/)![0];
 async function scales(name:string){for(const n of [1,3,4]){await p.setViewportSize({width:n*240,height:n*160});await capture(`b4-${name}-${n}x.png`,n);}await p.setViewportSize({width:960,height:640});}
 await scales('player-menu');await key(p,'ArrowUp');await expect(p.getByRole('button',{name:'POKÉDEX',exact:true})).toHaveAttribute('aria-current','true');await key(p,'Enter',500);await scales('pokedex');await key(p,'ArrowRight');await capture('b4-pokedex-language-4x.png',4);await key(p,'ArrowDown');await key(p,'ArrowDown');await key(p,'Enter');await scales('pokedex-detail');await key(p,'ArrowRight');await key(p,'Enter');await expect(p.getByRole('region',{name:'Project detail'})).toBeVisible();await capture('b4-pokedex-related-project-4x.png',4);await key(p,'Backspace');await expect(p.getByRole('region',{name:'Pokédex detail'})).toContainText('PYTHON');await key(p,'ArrowDown');await expect(p.getByRole('region',{name:'Pokédex detail'})).toContainText('GO');await key(p,'Backspace');await key(p,'Backspace',500);
 await menuItem(p,'PROJECTS');await scales('projects');const found=new Set<string>();for(let i=0;i<12;i++){const rows=p.getByRole('region',{name:'Projects catalogue'}).getByRole('button');for(const name of await rows.evaluateAll(ns=>ns.map(n=>n.getAttribute('aria-label')!)))found.add(name);if(i<11)await key(p,'ArrowDown');}expect([...found].sort()).toEqual(PORTFOLIO_PROJECTS.map(p=>p.name).sort());await capture('b4-projects-last-row-4x.png',4);await key(p,'Enter');await scales('project-overview');await key(p,'ArrowRight');await capture('b4-project-tech-impact-4x.png',4);await key(p,'ArrowRight');await capture('b4-project-links-4x.png',4);await key(p,'Backspace');await expect(p.getByRole('button',{name:'ChatRoomApp',exact:true})).toHaveAttribute('aria-current','true');await key(p,'Backspace',500);
 await menuItem(p,'EXPERIENCE');await scales('experience');await key(p,'ArrowRight');await capture('b4-experience-ownership-4x.png',4);await key(p,'Enter');await capture('b4-experience-next-page-4x.png',4);await key(p,'ArrowDown');await capture('b4-experience-research-4x.png',4);await key(p,'Backspace');await key(p,'Backspace',500);
 await menuItem(p,'BAG');await scales('bag-documents');await key(p,'ArrowRight');await capture('b4-bag-profiles-4x.png',4);await key(p,'ArrowRight');await capture('b4-bag-contact-4x.png',4);await expect(p.getByRole('region',{name:'Bag'})).toContainText('uttkarshmalviya@gmail.com');await key(p,'ArrowRight');await capture('b4-bag-extras-4x.png',4);await key(p,'Enter');await expect(p.getByRole('button',{name:'Reveal dialogue'})).toBeVisible();await p.getByRole('button',{name:'Reveal dialogue'}).click();await capture('b4-bag-achievements-4x.png',4);for(let i=0;i<10&&await p.getByRole('button',{name:/dialogue/}).count();i++){const reveal=p.getByRole('button',{name:'Reveal dialogue'});if(await reveal.isVisible())await reveal.click();else await p.getByRole('button',{name:'Continue dialogue'}).click();await tick(p,50);}await key(p,'Backspace',500);
 await menuItem(p,'UTTKARSH');await scales('trainer-card');await key(p,'Enter');await expect(p.getByRole('region',{name:'Trainer Card'})).toBeVisible();await expect(p.getByRole('region',{name:'Trainer Card'}).locator('[data-cursor]')).toHaveCount(0);await key(p,'Backspace',500);
 await menuItem(p,'OPTIONS');await scales('options');for(let i=0;i<2;i++)await key(p,'ArrowDown');await key(p,'ArrowRight');expect(await p.evaluate(()=>JSON.parse(localStorage.getItem('uw.settings.v1')!).textSpeed)).toBe('fast');await key(p,'ArrowDown');await key(p,'ArrowRight');expect(await p.evaluate(()=>JSON.parse(localStorage.getItem('uw.settings.v1')!).animationReduced)).toBe(true);await key(p,'ArrowDown');await key(p,'ArrowDown');await key(p,'Enter');await scales('controls');const controlsText=await p.getByRole('region',{name:'Controls'}).locator('[data-bitmap-text]').last().getAttribute('data-bitmap-text');expect(controlsText).not.toContain('\\n');expect(controlsText).toContain('\nENTER A: CONFIRM');await key(p,'Backspace');await key(p,'ArrowDown');await key(p,'Enter');await capture('b4-options-reset-4x.png',4);await key(p,'Backspace',500);
 await menuItem(p,'EXIT');await expect(p.getByRole('button',{name:'NO',exact:true})).toHaveAttribute('aria-current','true');await scales('exit-confirmation');await key(p,'Enter');await expect(p.getByRole('button',{name:'EXIT',exact:true})).toHaveAttribute('aria-current','true');await key(p,'x');await expect(p.getByRole('navigation',{name:'Player Menu'})).toHaveCount(0);await expect(world).toContainText(anchor);await key(p,'x');await expect(p.getByRole('button',{name:'EXIT',exact:true})).toHaveAttribute('aria-current','true');await p.setViewportSize({width:1440,height:900});await capture('b4-player-menu-largest-fit.png',5);await key(p,'Enter');await key(p,'ArrowUp');await key(p,'Enter',300);await expect(p).toHaveURL(/\/about$/);await expect(p.getByRole('heading',{name:'Uttkarsh Malviya',exact:true})).toBeVisible();expect(errors).toEqual([]);await c.close();
});
test('B4 direct Y to Resume, external profiles, unsafe/failed resources and semantic fallbacks',async({browser})=>{
 const c=await browser.newContext({viewport:{width:960,height:640}}),p=await c.newPage();await start(p);await key(p,'y',500);await expect(p.getByRole('button',{name:'RESUME',exact:true})).toHaveAttribute('aria-current','true');const popup=c.waitForEvent('page');const downloaded=new Promise<Download>(resolve=>{p.once('download',resolve);c.once('page',page=>page.once('download',resolve));});await p.keyboard.press('Enter');const resume=await popup;const pdf=await downloaded;expect(pdf.url()).toMatch(/\/documents\/Uttkarsh_Malviya\.pdf$/);expect(pdf.suggestedFilename()).toBe('Uttkarsh_Malviya.pdf');const response=await p.request.get('/documents/Uttkarsh_Malviya.pdf');expect(response.headers()['content-type']).toContain('application/pdf');expect(createHash('sha256').update(await response.body()).digest('hex')).toBe('1c2a144d5d245a874879f4423c7ca87831eed7002a3efa8435d8e58b65669f5e');await resume.close();await tick(p,800);await key(p,'ArrowRight');const opened=c.waitForEvent('page');await p.keyboard.press('Enter');const github=await opened;await github.waitForURL(/github.com/);await github.close();await tick(p,900);await key(p,'ArrowLeft');await expect(p.getByRole('button',{name:'CERTIFICATES',exact:true})).toHaveAttribute('aria-disabled','true');
 await p.evaluate(()=>{const calls:string[]=[];Object.assign(window,{__portfolioLinks:calls});window.open=(url)=>{calls.push(String(url));return null;};});await key(p,'ArrowRight');await key(p,'ArrowDown');await key(p,'Enter');expect(await p.evaluate(()=>(window as unknown as {__portfolioLinks:string[]}).__portfolioLinks.at(-1))).toBe('https://www.linkedin.com/in/uttkarsh-malviya-373231130/');await tick(p,800);await key(p,'ArrowRight');await key(p,'Enter');expect(await p.evaluate(()=>(window as unknown as {__portfolioLinks:string[]}).__portfolioLinks.at(-1))).toBe('mailto:uttkarshmalviya@gmail.com');await tick(p,800);await key(p,'ArrowLeft');
 await p.evaluate(()=>{window.open=()=>{throw new Error('blocked');};});await key(p,'Enter');await expect(p.getByRole('region',{name:'Bag'})).toContainText("Couldn't open that.");
 const html=await c.newPage();await html.goto('/resume');await expect(html.getByRole('link',{name:'Open original resume PDF'})).toHaveAttribute('href','/documents/Uttkarsh_Malviya.pdf');await html.goto('/projects');await expect(html.getByRole('main').getByRole('heading',{level:2})).toHaveCount(12);await html.goto('/skills');expect(await html.getByRole('main').getByRole('heading',{level:3}).count()).toBe(SKILLS.length);await html.goto('/experience');await expect(html.getByRole('heading',{name:/Professional Experience/i})).toBeVisible();await html.goto('/projects/pdf-qa');await expect(html.getByRole('heading',{name:'PDF-QA',exact:true})).toBeVisible();await expect(html.locator('canvas')).toHaveCount(0);await c.close();
});
test('B4 touch intent parity, external controller clearance and menu pixel raster at DPR 3',async({browser})=>{
 fs.mkdirSync(output,{recursive:true});const c=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true}),p=await c.newPage(),capture=recorder(p,3,'b4-touch-captures.json');await start(p,true);const controller=p.getByLabel('Touch controller');await expect(controller).toBeVisible();await p.getByRole('button',{name:'Menu (X)'}).tap();await tick(p,120);await expect(p.getByRole('navigation',{name:'Player Menu'})).toBeVisible();const n=Number(await p.getByRole('region',{name:'Game frame'}).getAttribute('data-scale'));await capture('b4-touch-player-menu.png',n);
 const before=await p.getByRole('status',{name:'Game state'}).innerText();await p.getByRole('button',{name:'Move down'}).tap();await tick(p,500);expect(await p.getByRole('status',{name:'Game state'}).innerText()).toBe(before);await p.getByRole('button',{name:'A confirm'}).tap();await tick(p,500);await expect(p.getByRole('region',{name:'Projects catalogue'})).toBeVisible();await capture('b4-touch-projects.png',n);await p.getByRole('button',{name:'Bag (Y)'}).tap();await tick(p,500);await expect(p.getByRole('region',{name:'Bag'})).toBeVisible();await capture('b4-touch-bag.png',n);const frame=(await p.getByRole('region',{name:'Game frame'}).boundingBox())!;for(const b of await controller.locator('button').all()){const bounds=(await b.boundingBox())!;expect(bounds.width).toBeGreaterThanOrEqual(48);expect(bounds.height).toBeGreaterThanOrEqual(48);expect(bounds.y>=frame.y+frame.height||bounds.x+bounds.width<=frame.x||bounds.x>=frame.x+frame.width).toBe(true);}await c.close();
 const desktop=await browser.newContext({viewport:{width:320,height:214},deviceScaleFactor:3}),q=await desktop.newPage();await start(q);await key(q,'x');await key(q,'Enter',500);await recorder(q,3,'b4-dpr-3-captures.json')('b4-pokedex-dpr-3-4x.png',4);await desktop.close();
});
