'use client';
import {getPortfolioProjects,getSkillCategories,getSkills,getSkillProjects,getExperiences,getTrainerCard,getBagCategories,PLAYER_MENU,getProjectTech,getProjectWriteup} from '../../content/portfolio';
import type {ProjectDef} from '../../domain/types';
import {BattleArtwork} from '../battle/BattleArtwork';
import {PortfolioArt,type PortfolioAsset} from './PortfolioArt';
import {Header,Screen,Text,Row,Rect,Divider,ScrollArrows,box,firstRow,pages} from './layout';
import {Window} from '../kit/Window';
import {palette} from '../kit/palette';
import {glyphAdvance} from '../kit/text';
import type {PortfolioView} from '../../domain/menu';
export type {PortfolioScreen,PortfolioView} from '../../domain/menu';
export {OPTION_LABELS} from '../../content/portfolio';
export const MENU_ITEMS=PLAYER_MENU.map(item=>item.label);
const PORTFOLIO_PROJECTS=getPortfolioProjects(),SKILL_CATEGORIES=getSkillCategories(),EXPERIENCE=getExperiences(),PROFILE=getTrainerCard(),BAG=getBagCategories();
const categoryShort:Record<string,string>={LANGUAGE:'LANG',BACKEND:'BACK',DISTRIBUTED:'DIST',DATABASE:'DATA',CLOUD:'CLOUD',DEVOPS:'OPS',OBSERVABILITY:'OBS',FRONTEND:'APP',CONCEPT:'IDEA'};
export function typeLabel(type:string){return type.toUpperCase().replace(/_/g,'');}
export function Dex({view,tap,category,related}:{view:PortfolioView;tap:(i:number)=>void;category:(delta:number)=>void;related:(i:number)=>void}){
 const entries=getSkills(view.category);const skill=entries[view.cursor];
 if(view.screen==='dex-detail'&&skill){const body=pages(skill.description,178,4),links=getSkillProjects(view.category,view.cursor).slice(0,3);return <Screen name="Pokédex detail"><Header name={skill.name}/><PortfolioArt name={(skill.category.toLowerCase()+'-badge') as PortfolioAsset} x={177} y={11}/><Text text={categoryShort[skill.type]!} x={190} y={11} color={palette.onDark}/><span className="sr-only">Type: {skill.type}</span><PortfolioArt name={(skill.category.toLowerCase()+'-large') as PortfolioAsset} x={11} y={29}/><Text text={body[view.page%body.length]!} x={51} y={29} width={178} pitch={10}/>{body.length>1&&<Text text="▼" x={225} y={65}/>}<Divider y={73}/><Text text="WHERE USED" x={11} y={77} color={palette.header}/><Text text={skill.whereUsed} x={11} y={89} width={218} maxLines={2} pitch={10}/>{links.map((project,i)=><Row key={project.id} name={`Related project: ${project.name}`} selected={!!view.relatedFocus&&view.related===i} y={109+i*13} height={13} onTap={()=>related(i)}><Text text={project.visual.plateName!} x={8} y={0} width={210} maxLines={1}/></Row>)}</Screen>;}
 const start=firstRow(view.cursor,8);return <Screen name="Pokédex"><Header name="POKÉDEX" right={SKILL_CATEGORIES[view.category]} onLeft={()=>category(-1)} onRight={()=>category(1)}/>{entries.slice(start,start+8).map((entry,offset)=>{const i=start+offset;return <Row name={entry.name} key={entry.id} y={25+offset*16} selected={view.cursor===i} pressed={view.pressed===i} onTap={()=>tap(i)}><PortfolioArt name={entry.category.toLowerCase() as PortfolioAsset} x={8}/><Text text={entry.name} x={28} y={1} width={138} maxLines={1}/><PortfolioArt name={(entry.category.toLowerCase()+'-badge') as PortfolioAsset} x={170} y={1}/><Text text={categoryShort[entry.type]!} x={218-[...categoryShort[entry.type]!].reduce((sum,c)=>sum+glyphAdvance(c),0)} y={1}/><span className="sr-only">Category: {entry.type}</span></Row>;})}<ScrollArrows start={start} total={entries.length}/>{view.notice&&<span role="status" className="sr-only">{view.notice}</span>}</Screen>;
}
function ProjectIdentity({project}:{project:ProjectDef}){return <><PortfolioArt name={`project-${project.slug}-48` as PortfolioAsset} x={11} y={29}/><Text text={project.visual.plateName!} x={65} y={29} width={160} maxLines={1}/><Text text={typeLabel(project.type)} x={65} y={41}/><Text text={`ROLE ${project.role==='Project author'?'AUTHOR':project.role.toUpperCase()}\nPERIOD ${project.period==='Not specified'?'NOT SUPPLIED':project.period}${project.team?`\nTEAM ${project.team}`:''}`} x={65} y={55} width={164} pitch={10}/></>;}
export function Projects({view,tap,page,link}:{view:PortfolioView;tap:(i:number)=>void;page:(d:number)=>void;link:(url:string,name:string)=>void}){
 const project=PORTFOLIO_PROJECTS[view.project]??PORTFOLIO_PROJECTS[0]!;
 if(view.screen==='project-detail'){
  const labels=['OVERVIEW','TECH & IMPACT','LINKS'];return <Screen name="Project detail"><Header name="PROJECTS" right={`${labels[view.section]} ${view.section+1}/3`} onLeft={()=>page(-1)} onRight={()=>page(1)}/>{view.section===0?<><ProjectIdentity project={project}/><Text text={pages(project.summary.pages.join(' '),218,7)[view.page%pages(project.summary.pages.join(' '),218,7).length]!} x={11} y={81} width={218} pitch={10}/></>:view.section===1?<><Text text="TECH" x={11} y={29} color={palette.header}/><Text text={pages(getProjectTech(project.id).map(s=>s.name).join(', '),218,3)[view.page%pages(getProjectTech(project.id).map(s=>s.name).join(', '),218,3).length]!} x={11} y={41} width={218} pitch={10}/><Divider y={73}/><Text text="IMPACT" x={11} y={77} color={palette.header}/><Text text={pages(project.impact.join(' ')||getProjectWriteup(project.id).find(e=>/impact|changed|result|proud/i.test(e.question))?.text||'No authored impact facts supplied.',218,5)[view.page%pages(project.impact.join(' ')||getProjectWriteup(project.id).find(e=>/impact|changed|result|proud/i.test(e.question))?.text||'No authored impact facts supplied.',218,5).length]!} x={11} y={89} width={218} pitch={10}/></>:<>{[project.links.primary,...project.links.others,{label:'FULL WRITE-UP',url:`/projects/${project.slug}`}].map((item,i)=><Row key={item.url} name={item.label} selected={view.cursor===i} pressed={view.pressed===i} y={29+i*16} onTap={()=>tap(i)}><Text text={item.label.toUpperCase()} x={8} y={0} width={192} maxLines={1}/><Text text="↗" x={210} y={0}/></Row>)}{view.notice&&<Text text={view.notice} x={11} y={137} width={218} maxLines={2} pitch={10}/>}</>}{view.section===0&&<button className="sr-only" onClick={()=>link(`/projects/${project.slug}`,'FULL WRITE-UP')}>Open full project write-up</button>}</Screen>;
 }
 const start=firstRow(view.cursor,7);return <Screen name="Projects catalogue"><Header name="PROJECTS"/>{PORTFOLIO_PROJECTS.slice(start,start+7).map((project,offset)=>{const i=start+offset,type=typeLabel(project.type),w=[...type].reduce((a,c)=>a+glyphAdvance(c),0);return <Row name={project.name} key={project.id} selected={view.cursor===i} pressed={view.pressed===i} y={25+offset*16} onTap={()=>tap(i)}><BattleArtwork name={`thumb-${project.slug}`} x={8}/><Text text={project.visual.shortName!} x={28} y={1} width={75} maxLines={1}/><BattleArtwork name={`type-${String(project.type)}`} x={210-w-18} y={3}/><Text text={type} x={218-w} y={1}/></Row>;})}<Divider y={135}/><Text text={PORTFOLIO_PROJECTS[view.cursor]?.visual.tagline??''} x={11} y={139} width={218} maxLines={1}/><ScrollArrows start={start} total={PORTFOLIO_PROJECTS.length} visible={7}/></Screen>;
}
export function Experience({view,tap,section}:{view:PortfolioView;tap:(i:number)=>void;section:(d:number)=>void}){
 const role=EXPERIENCE[view.cursor]!,selected=role.sections[view.section]!,body=pages(selected.text,218,5),start=firstRow(view.cursor,3);
 return <Screen name={view.screen==='experience-detail'?'Experience detail':'Experience'}><Header name="EXPERIENCE"/>{EXPERIENCE.slice(start,start+3).map((entry,offset)=>{const i=start+offset;return <Row key={entry.id} name={entry.company} selected={view.cursor===i} pressed={view.pressed===i} y={25+offset*16} onTap={()=>tap(i)}><Text text={entry.company} x={8} y={0}/><Text text={entry.shortPeriod} x={218-[...entry.shortPeriod].reduce((a,c)=>a+glyphAdvance(c),0)} y={0}/></Row>;})}<span className="sr-only">{role.company}; {role.role}; {role.period}</span><Divider y={77}/><button aria-label="Previous experience section" onClick={()=>section(-1)} style={box(11,79,12,16)}><Text text="◂" x={0} y={2}/></button><Text text={`${selected.name} ${view.section+1}/${role.sections.length}`} x={27} y={81} color={palette.header}/><button aria-label="Next experience section" onClick={()=>section(1)} style={box(217,79,12,16)}><Text text="▸" x={0} y={2}/></button><Text text={body[view.page%body.length]!} x={11} y={97} width={218} pitch={10}/>{body.length>1&&<Text text="▼" x={225} y={145}/>}</Screen>;
}
export function Bag({view,tap,category}:{view:PortfolioView;tap:(i:number)=>void;category:(d:number)=>void}){
 const current=BAG[view.category]!,start=firstRow(view.cursor,5),item=current.items[view.cursor];return <section aria-label="Bag" data-portfolio-screen="Bag" aria-hidden={view.screen==='bag-reading'||undefined} inert={view.screen==='bag-reading'} style={box(0,0,240,160)}><Window style={{...box(0,0,240,112),padding:0}}><Header name="" right={current.name} onLeft={()=>category(-1)} onRight={()=>category(1)} icon={<PortfolioArt name={current.art as PortfolioAsset} x={11} y={7}/>}/>{current.items.slice(start,start+5).map((item,offset)=>{const i=start+offset;return <Row name={item.name} selected={i===view.cursor} pressed={view.pressed===i} key={item.id} y={25+offset*16} disabled={!item.url&&!item.text} onTap={()=>tap(i)}><PortfolioArt name={item.art as PortfolioAsset} x={8}/><Text text={item.name} x={28} y={1} color={item.url||item.text?undefined:palette.disabled}/>{item.url&&<Text text="↗" x={210} y={1}/>}</Row>})}{!item&&<Text text="(EMPTY)" x={15} y={25}/>}</Window><Window style={{...box(0,112,240,48),padding:0}}><Text text={view.notice??item?.description??'Nothing here yet.'} x={7} y={7} width={226} maxLines={2}/>{item&&(item.url||item.text)&&<Text text="A: USE" x={196} y={34}/>}<span role="status" className="sr-only">{view.notice??item?.description??'Nothing here yet.'} A/Enter: use selected item. B/Backspace: back.</span></Window></section>;
}
export function TrainerCard(){return <Screen name="Trainer Card" fill="gold">{(['NAME','TITLE','ROLE','FOCUS','SCHOOL'] as const).map((key,i)=><div key={key}><Text text={key} x={15} y={15+16*i} color={palette.header}/><Text text={PROFILE[key.toLowerCase() as keyof typeof PROFILE] as string} x={57} y={15+16*i} width={106} maxLines={1}/></div>)}<Text text={PROFILE.qualification} x={15} y={95} width={210} maxLines={1}/><span className="sr-only">{PROFILE.positioning}. {PROFILE.education}.</span><Rect x={168} y={15} width={56} height={72} color={palette.inner} outline/><PortfolioArt name="trainer-portrait" x={172} y={19} label="Original portrait of Uttkarsh"/><Divider y={113}/><Text text={[...PROFILE.highlights,'Y: BAG FOR RESUME & LINKS'].join('\n')} x={15} y={117} width={210} pitch={10}/></Screen>;}
